### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by sengiv** [brother-yan/LGTISP#4]
I was thinking to throw out my lgt8f328p (bricked with bad code),
your work here saved it! Thanks!!

Please correct me if I'm wrong,
this LGTISP is **only** for burning bootloader into target board, correct?
Because I tried to burn the Blink sketch, and it got sync errors.

**Comment by dbuezas** [comment]
It should also upload "bootloader-less" sketches. I did it successfully a couple of times. Are you using short cables?

**Comment by sengiv** [comment]
thanks 4 quick reply,
my cables are 10cm long, I shall try with short ones.

But I have to ask, how does this make  a difference?
Interference? If so, lets say I twist them with ground, might help?

Will experiment and report back soon...

**Comment by Yodinsn** [comment]
thanks!!!
